version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore: "
    groups:
      baseimages:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(ci): "
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
