site_name: Cat Page
repo_url: https://github.com/radiorabe/cat-page
repo_name: radiorabe/cat-page

theme:
  name: "material"
  custom_dir: docs/overrides
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: '#00c9bf'
      accent: '#00c9bf'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: '#00c9bf'
      accent: '#00c9bf'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: material/radio
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
- admonition
- attr_list
- md_in_html
- toc:
    permalink: true
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
- css/style.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/radiorabe/cat-page
      name: GitHub
  generator: false

plugins:
- search
- section-index
- autorefs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Contributing: contributing.md
