[tool.poetry]
name = "cat-page"
version = "0.0.0" # 0.0.0 placeholder is replaced on release
description = "RaBe Cat Landing Page"
repository = "https://github.com/radiorabe/cat-page"
authors = ["RaBe IT-Reaktion <it@rabe.ch>"]
license = "AGPL-3"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Topic :: Multimedia :: Sound/Audio :: Conversion",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
readme = "README.md"
packages = [
    { include = "app"},
]

[tool.poetry.scripts]
catpage = 'app.server:main'

[tool.poetry.dependencies]
python = "^3.9"
Werkzeug = "^3.0.1"
Jinja2 = "^3.1.3"
configargparse = "^1.7"
CherryPy = "^18.9.0"
cachelib = "^0.12.0"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
flake8 = "^7.0.0"
flake8-debugger = "^4.1.2"
flake8-docstrings = "^1.6.0"
flake8-isort = "^6.1.1"
flake8-string-format = "^0.3.0"
flake8-tuple = "^0.4.1"
isort = "^5.13.2"
pydocstyle = "^6.1.1"
pytest = "^8.0.0"
pytest-cov = "^4.0.0"
pytest-random-order = "^1.1.1"
pytest-ruff = "^0.2"
ruff = "^0.2.1"

[tool.isort]
line_length = 120
profile = "black"

[tool.pytest.ini_options]
minversion = "7.2"
addopts = "-ra -q --random-order --doctest-glob='*.md' --doctest-modules --cov=app --cov-fail-under=100 --ruff --ignore docs/"
filterwarnings = ["ignore::pytest.PytestRemovedIn8Warning:pytest_pylint", "ignore::DeprecationWarning:cherrypy", "ignore::DeprecationWarning:pylint", "ignore::DeprecationWarning:pkg_resources", "ignore::DeprecationWarning:pytest_pylint"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
