name: Test

on:
  pull_request:

jobs:
  pre-commit:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@v0.16.1
  python-poetry:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@v0.16.1
  helm-chart:
    name: Test Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build dev image
        run: |
          docker build -t ghcr.io/radiorabe/catpage:latest -f Dockerfile .
          docker save -o /tmp/catpage.tar ghcr.io/radiorabe/catpage:latest

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --config=.github/ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct --config=.github/ct.yaml lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Load dev image
        run: |
          kind load image-archive /tmp/catpage.tar --name chart-testing

      - name: Run chart-testing (install)
        run: ct --config=.github/ct.yaml install
