name: Test and Release

on:
  pull_request:
  push:
    branches:
    tags:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - uses: pre-commit/action@v2.0.0
    - name: Test
      run: |
        pytest --cov=app --cov-report=term --cov-fail-under=100
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: radiorabe/catpage
        add_git_labels: true
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: go-semantic-release/action@v1.4.0
      with:
        github-token: ${{ secrets.GH_PAT_TOKEN }}
