name: Test

on:
  pull_request:

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@main
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x', '3.9' ]
    name: Test python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test
      run: |
        pytest --cov=app --cov-report=term --cov-fail-under=100
