name: Test

on:
  pull_request:

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@main
  call-workflow:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@main
