name: Test

on:
  pull_request:

jobs:
  pre-commit:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@main
  python-poetry:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@main
