name: Test and Release

on:
  pull_request:
  push:
    branches:
    tags:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - uses: pre-commit/action@v2.0.0
    - name: Test
      run: |
        pytest --cov=app --cov-report=term --cov-fail-under=100
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v3.6.0
      with:
        images: ghcr.io/radiorabe/catpage
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: go-semantic-release/action@v1.15
      with:
        github-token: ${{ secrets.GH_PAT_TOKEN }}
