name: Release

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'

permissions: {}

jobs:
  release-container:
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    uses: radiorabe/actions/.github/workflows/release-container.yaml@3f1ee42ffa54794a512d3989c34e3b4514de64cc # v0.43.1
    with:
      image: 'ghcr.io/radiorabe/catpage'
      name: 'catpage'
      display-name: 'Cat Page'
      tags: 'minimal rhel9 rabe s2i python python311 catpage'
  release-mkdocs:
    permissions:
      contents: write
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@3f1ee42ffa54794a512d3989c34e3b4514de64cc # v0.43.1
  helm-chart:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - release-container
    permissions:
      contents: read
      packages: write # for pushing to GitHub Container Registry
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Prepare Chart Metadata
        id: chartmeta
        run: echo version=${GITHUB_REF#refs/tags/v} >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.20.1

      - name: Package Chart
        env:
          STEPS_CHARTMETA_VERSION: ${{ steps.chartmeta.outputs.version }}
        run: helm package --version ${STEPS_CHARTMETA_VERSION} --app-version ${STEPS_CHARTMETA_VERSION} --destination=dist charts/catpage

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Chart
        run: helm push dist/*.tgz oci://ghcr.io/radiorabe/helm
