name: Scheduled tasks

on:
  schedule:
    - cron:  '13 12 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  schedule-trivy:
    permissions:
      packages: write
      security-events: write
      id-token: write
    uses: radiorabe/actions/.github/workflows/schedule-trivy.yaml@5459c6e6550bcc6969303a65ef6c44bb1cd0ccf1 # v0.43.2
    with:
      image-ref: 'ghcr.io/radiorabe/catpage:latest'
