name: Semantic Release

on:
  push:
    branches:
      - main
      - release/*

permissions: {}

jobs:
  semantic-release:
    permissions:
      contents: read
    uses: radiorabe/actions/.github/workflows/semantic-release.yaml@5459c6e6550bcc6969303a65ef6c44bb1cd0ccf1 # v0.43.2
    secrets:
      RABE_ITREAKTION_GITHUB_TOKEN: ${{ secrets.RABE_ITREAKTION_GITHUB_TOKEN }}
